const Images = {
    Logo : require('../assets/Image/Logo.png'),
    Google: require('../assets/Image/Google.png'),
    apple: require('../assets/Image/apple.png'),
    facebook: require('../assets/Image/facebook.png'),
    Notification: require('../assets/Image/Notification.png'),
    RickshaaIcon: require('../assets/Image/RickshaaIcon.png'),
    RickshaaIcon1: require('../assets/Image/RickshaaIcon1.png'), //icons8-usa-60.png
    usa: require('../assets/Image/usa.png'),
    ImageBackground: require('../assets/Image/ImageBackground.jpg'),
    KadaiPaneer: require('../assets/Image/KadaiPaneer.jpg'),
    burger: require('../assets/Image/burger.jpg'),
    noodles: require('../assets/Image/noodles.png'),
    soyaChaap: require('../assets/Image/soyaChaap.jpg'),
    pizza: require('../assets/Image/pizza.jpg'),
    chinese: require('../assets/Image/chinese.jpg'), //fastFood
    fastFood: require('../assets/Image/fastFood.jpg'),
    wings: require('../assets/Image/wings.jpg'),
    sushi: require('../assets/Image/sushi.jpg'),
    indian: require('../assets/Image/indian.jpg'),
    thai: require('../assets/Image/thai.jpg'),
    dalMakhani: require('../assets/Image/dalMakhani.jpg'),
    addtip: require('../assets/Image/addtip.png'),
    privacyPolicy: require('../assets/Image/privacyPolicy.png'),
    about: require('../assets/Image/about.png'),
    bubbleTea: require('../assets/Image/bubbleTea.jpg'),
    desserts: require('../assets/Image/desserts.jpg'),
    success_1: require('../assets/Image/success_1.gif'),
    iconOfficial: require('../assets/Image/iconOfficial.png'),
    termsCondition: require('../assets/Image/termsCondition.png'),
    demo1: require('../assets/Image/demo1.png'),
    demo2: require('../assets/Image/demo2.png'),
    banner: require('../assets/Image/banner.jpg'),
    notFound: require('../assets/Image/notFound.jpg'),
}
export default Images;